import type { Payment } from './columns';

export const data: Payment[] = [
    {
        id: '728ed52f',
        name: 'Morgan',
        email: 'morgan@example.com',
        gender: 'male',
        role: 'Admin',
        amount: 100,
        status: 'pending',
    },
    {
        id: '728ee6d2',
        name: 'Ada',
        email: 'ada@example.com',
        gender: 'female',
        role: 'Editor',
        amount: 250,
        status: 'processing',
    },
    {
        id: '728ef875',
        name: 'Ben',
        email: 'ben@example.com',
        gender: 'male',
        role: 'Viewer',
        amount: 75,
        status: 'success',
    },
    {
        id: '728f0a18',
        name: 'Cara',
        email: 'cara@example.com',
        gender: 'female',
        role: 'Manager',
        amount: 420,
        status: 'failed',
    },
    {
        id: '728f1bbb',
        name: 'Dan',
        email: 'dan@example.com',
        gender: 'male',
        role: 'Analyst',
        amount: 15,
        status: 'pending',
    },
    {
        id: '728f2d5e',
        name: 'Elena',
        email: 'elena@example.com',
        gender: 'female',
        role: 'Support',
        amount: 980,
        status: 'processing',
    },
    {
        id: '728f3f01',
        name: 'Farid',
        email: 'farid@example.com',
        gender: 'male',
        role: 'Admin',
        amount: 310,
        status: 'success',
    },
    {
        id: '728f50a4',
        name: 'Gina',
        email: 'gina@example.com',
        gender: 'female',
        role: 'Editor',
        amount: 55,
        status: 'failed',
    },
    {
        id: '728f6247',
        name: 'Hugo',
        email: 'hugo@example.com',
        gender: 'male',
        role: 'Viewer',
        amount: 1200,
        status: 'pending',
    },
    {
        id: '728f73ea',
        name: 'Iris',
        email: 'iris@example.com',
        gender: 'female',
        role: 'Manager',
        amount: 88,
        status: 'processing',
    },
    {
        id: '728f858d',
        name: 'Jake',
        email: 'jake@example.com',
        gender: 'male',
        role: 'Analyst',
        amount: 640,
        status: 'success',
    },
    {
        id: '728f9730',
        name: 'Kira',
        email: 'kira@example.com',
        gender: 'female',
        role: 'Support',
        amount: 199,
        status: 'failed',
    },
    {
        id: '728fa8d3',
        name: 'Leo',
        email: 'leo@example.com',
        gender: 'male',
        role: 'Admin',
        amount: 32,
        status: 'pending',
    },
    {
        id: '728fba76',
        name: 'Maya',
        email: 'maya@example.com',
        gender: 'female',
        role: 'Editor',
        amount: 475,
        status: 'processing',
    },
    {
        id: '728fcc19',
        name: 'Noah',
        email: 'noah@example.com',
        gender: 'male',
        role: 'Viewer',
        amount: 850,
        status: 'success',
    },
    {
        id: '728fddbc',
        name: 'Olivia',
        email: 'olivia@example.com',
        gender: 'female',
        role: 'Manager',
        amount: 12,
        status: 'failed',
    },
    {
        id: '728fef5f',
        name: 'Paul',
        email: 'paul@example.com',
        gender: 'male',
        role: 'Analyst',
        amount: 1500,
        status: 'pending',
    },
    {
        id: '72900102',
        name: 'Quinn',
        email: 'quinn@example.com',
        gender: 'female',
        role: 'Support',
        amount: 67,
        status: 'processing',
    },
    {
        id: '729012a5',
        name: 'Riley',
        email: 'riley@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 225,
        status: 'success',
    },
    {
        id: '72902448',
        name: 'Sara',
        email: 'sara@example.com',
        gender: 'female',
        role: 'Editor',
        amount: 399,
        status: 'failed',
    },
    {
        id: '729035eb',
        name: 'Tom',
        email: 'tom@example.com',
        gender: 'male',
        role: 'Viewer',
        amount: 110,
        status: 'pending',
    },
    {
        id: '7290478e',
        name: 'Uma',
        email: 'uma@example.com',
        gender: 'female',
        role: 'Manager',
        amount: 720,
        status: 'processing',
    },
    {
        id: '72905931',
        name: 'Victor',
        email: 'victor@example.com',
        gender: 'male',
        role: 'Analyst',
        amount: 48,
        status: 'success',
    },
    {
        id: '72906ad4',
        name: 'Wren',
        email: 'wren@example.com',
        gender: 'female',
        role: 'Support',
        amount: 2750,
        status: 'failed',
    },
    {
        id: '72907c77',
        name: 'Xavier',
        email: 'xavier@example.com',
        gender: 'male',
        role: 'Admin',
        amount: 165,
        status: 'pending',
    },
    {
        id: '72908e1a',
        name: 'Yara',
        email: 'yara@example.com',
        gender: 'female',
        role: 'Editor',
        amount: 90,
        status: 'processing',
    },
    {
        id: '72909fbd',
        name: 'Zane',
        email: 'zane@example.com',
        gender: 'male',
        role: 'Viewer',
        amount: 560,
        status: 'success',
    },
    {
        id: '7290b160',
        name: 'Alice',
        email: 'alice@example.com',
        gender: 'female',
        role: 'Manager',
        amount: 28,
        status: 'failed',
    },
    {
        id: '7290c303',
        name: 'Bruno',
        email: 'bruno@example.com',
        gender: 'male',
        role: 'Analyst',
        amount: 335,
        status: 'pending',
    },
    {
        id: '7290d4a6',
        name: 'Chloe',
        email: 'chloe@example.com',
        gender: 'female',
        role: 'Support',
        amount: 890,
        status: 'processing',
    },
    {
        id: '7290e649',
        name: 'Diego',
        email: 'diego@example.com',
        gender: 'male',
        role: 'Admin',
        amount: 140,
        status: 'success',
    },
    {
        id: '7290f7ec',
        name: 'Eva',
        email: 'eva@example.com',
        gender: 'female',
        role: 'Editor',
        amount: 2100,
        status: 'failed',
    },
    {
        id: '7291098f',
        name: 'Finn',
        email: 'finn@example.com',
        gender: 'male',
        role: 'Viewer',
        amount: 73,
        status: 'pending',
    },
    {
        id: '72911b32',
        name: 'Grace',
        email: 'grace@example.com',
        gender: 'female',
        role: 'Manager',
        amount: 455,
        status: 'processing',
    },
    {
        id: '72912cd5',
        name: 'Henry',
        email: 'henry@example.com',
        gender: 'male',
        role: 'Analyst',
        amount: 18,
        status: 'success',
    },
    {
        id: '72913e78',
        name: 'Isla',
        email: 'isla@example.com',
        gender: 'female',
        role: 'Support',
        amount: 625,
        status: 'failed',
    },
    {
        id: '7291501b',
        name: 'James',
        email: 'james@example.com',
        gender: 'male',
        role: 'Admin',
        amount: 305,
        status: 'pending',
    },
    {
        id: '729161be',
        name: 'Kate',
        email: 'kate@example.com',
        gender: 'female',
        role: 'Editor',
        amount: 1750,
        status: 'processing',
    },
    {
        id: '72917361',
        name: 'Liam',
        email: 'liam@example.com',
        gender: 'male',
        role: 'Viewer',
        amount: 42,
        status: 'success',
    },
    {
        id: '72918504',
        name: 'Mia',
        email: 'mia@example.com',
        gender: 'female',
        role: 'Manager',
        amount: 780,
        status: 'failed',
    },
    {
        id: '729196a7',
        name: 'Nina',
        email: 'nina@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 215,
        status: 'pending',
    },
    {
        id: '7291a84a',
        name: 'Omar',
        email: 'omar@example.com',
        gender: 'male',
        role: 'Support',
        amount: 95,
        status: 'processing',
    },
    {
        id: '7291b9ed',
        name: 'Priya',
        email: 'priya@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 510,
        status: 'success',
    },
    {
        id: '7291cb90',
        name: 'Quentin',
        email: 'quentin@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 38,
        status: 'failed',
    },
    {
        id: '7291dd33',
        name: 'Rosa',
        email: 'rosa@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 990,
        status: 'pending',
    },
    {
        id: '7291eed6',
        name: 'Sam',
        email: 'sam@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 125,
        status: 'processing',
    },
    {
        id: '72920079',
        name: 'Tara',
        email: 'tara@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 3400,
        status: 'success',
    },
    {
        id: '7292121c',
        name: 'Uri',
        email: 'uri@example.com',
        gender: 'male',
        role: 'Support',
        amount: 60,
        status: 'failed',
    },
    {
        id: '729223bf',
        name: 'Vera',
        email: 'vera@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 445,
        status: 'pending',
    },
    {
        id: '72923562',
        name: 'Will',
        email: 'will@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 185,
        status: 'processing',
    },
    {
        id: '72924705',
        name: 'Zoe',
        email: 'zoe@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 22,
        status: 'success',
    },
    {
        id: '729258a8',
        name: 'Aaron',
        email: 'aaron@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 860,
        status: 'failed',
    },
    {
        id: '72926a4b',
        name: 'Bella',
        email: 'bella@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 41,
        status: 'pending',
    },
    {
        id: '72927bee',
        name: 'Carl',
        email: 'carl@example.com',
        gender: 'male',
        role: 'Support',
        amount: 91,
        status: 'processing',
    },
    {
        id: '72928d91',
        name: 'Dana',
        email: 'dana@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 270,
        status: 'success',
    },
    {
        id: '72929f34',
        name: 'Eric',
        email: 'eric@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 640,
        status: 'failed',
    },
    {
        id: '7292b0d7',
        name: 'Fiona',
        email: 'fiona@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 155,
        status: 'pending',
    },
    {
        id: '7292c27a',
        name: 'Gabe',
        email: 'gabe@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 88,
        status: 'processing',
    },
    {
        id: '7292d41d',
        name: 'Hana',
        email: 'hana@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 430,
        status: 'success',
    },
    {
        id: '7292e5c0',
        name: 'Ian',
        email: 'ian@example.com',
        gender: 'male',
        role: 'Support',
        amount: 77,
        status: 'failed',
    },
    {
        id: '7292f763',
        name: 'Jade',
        email: 'jade@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 520,
        status: 'pending',
    },
    {
        id: '72930906',
        name: 'Ken',
        email: 'ken@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 310,
        status: 'processing',
    },
    {
        id: '72931aa9',
        name: 'Lara',
        email: 'lara@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 64,
        status: 'success',
    },
    {
        id: '72932c4c',
        name: 'Max',
        email: 'max@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 1180,
        status: 'failed',
    },
    {
        id: '72933def',
        name: 'Nora',
        email: 'nora@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 200,
        status: 'pending',
    },
    {
        id: '72934f92',
        name: 'Oscar',
        email: 'oscar@example.com',
        gender: 'male',
        role: 'Support',
        amount: 49,
        status: 'processing',
    },
    {
        id: '72936135',
        name: 'Penny',
        email: 'penny@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 735,
        status: 'success',
    },
    {
        id: '729372d8',
        name: 'Ryan',
        email: 'ryan@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 160,
        status: 'failed',
    },
    {
        id: '7293847b',
        name: 'Sophie',
        email: 'sophie@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 27,
        status: 'pending',
    },
    {
        id: '7293961e',
        name: 'Theo',
        email: 'theo@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 940,
        status: 'processing',
    },
    {
        id: '7293a7c1',
        name: 'Una',
        email: 'una@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 105,
        status: 'success',
    },
    {
        id: '7293b964',
        name: 'Vince',
        email: 'vince@example.com',
        gender: 'male',
        role: 'Support',
        amount: 58,
        status: 'failed',
    },
    {
        id: '7293cb07',
        name: 'Wendy',
        email: 'wendy@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 1280,
        status: 'pending',
    },
    {
        id: '7293dcaa',
        name: 'York',
        email: 'york@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 33,
        status: 'processing',
    },
    {
        id: '7293ee4d',
        name: 'Amber',
        email: 'amber@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 470,
        status: 'success',
    },
    {
        id: '7293fff0',
        name: 'Blake',
        email: 'blake@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 81,
        status: 'failed',
    },
    {
        id: '72941193',
        name: 'Cindy',
        email: 'cindy@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 690,
        status: 'pending',
    },
    {
        id: '72942336',
        name: 'Derek',
        email: 'derek@example.com',
        gender: 'male',
        role: 'Support',
        amount: 19,
        status: 'processing',
    },
    {
        id: '729434d9',
        name: 'Ellen',
        email: 'ellen@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 560,
        status: 'success',
    },
    {
        id: '7294467c',
        name: 'Frank',
        email: 'frank@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 240,
        status: 'failed',
    },
    {
        id: '7294581f',
        name: 'Gwen',
        email: 'gwen@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 44,
        status: 'pending',
    },
    {
        id: '729469c2',
        name: 'Hank',
        email: 'hank@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 810,
        status: 'processing',
    },
    {
        id: '72947b65',
        name: 'Ivy',
        email: 'ivy@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 130,
        status: 'success',
    },
    {
        id: '72948d08',
        name: 'Joel',
        email: 'joel@example.com',
        gender: 'male',
        role: 'Support',
        amount: 36,
        status: 'failed',
    },
    {
        id: '72949eab',
        name: 'Kim',
        email: 'kim@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 1520,
        status: 'pending',
    },
    {
        id: '7294b04e',
        name: 'Luke',
        email: 'luke@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 70,
        status: 'processing',
    },
    {
        id: '7294c1f1',
        name: 'Marie',
        email: 'marie@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 265,
        status: 'success',
    },
    {
        id: '7294d394',
        name: 'Nick',
        email: 'nick@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 98,
        status: 'failed',
    },
    {
        id: '7294e537',
        name: 'Opal',
        email: 'opal@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 410,
        status: 'pending',
    },
    {
        id: '7294f6da',
        name: 'Pete',
        email: 'pete@example.com',
        gender: 'male',
        role: 'Support',
        amount: 54,
        status: 'processing',
    },
    {
        id: '7295087d',
        name: 'Rachel',
        email: 'rachel@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 875,
        status: 'success',
    },
    {
        id: '72951a20',
        name: 'Steve',
        email: 'steve@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 145,
        status: 'failed',
    },
    {
        id: '72952bc3',
        name: 'Tina',
        email: 'tina@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 29,
        status: 'pending',
    },
    {
        id: '72953d66',
        name: 'Ulysses',
        email: 'ulysses@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 1960,
        status: 'processing',
    },
    {
        id: '72954f09',
        name: 'Violet',
        email: 'violet@example.com',
        gender: 'female',
        role: 'Analyst',
        amount: 82,
        status: 'success',
    },
    {
        id: '729560ac',
        name: 'Wayne',
        email: 'wayne@example.com',
        gender: 'male',
        role: 'Support',
        amount: 355,
        status: 'failed',
    },
    {
        id: '7295724f',
        name: 'Yolanda',
        email: 'yolanda@example.com',
        gender: 'female',
        role: 'Admin',
        amount: 61,
        status: 'pending',
    },
    {
        id: '729583f2',
        name: 'Zach',
        email: 'zach@example.com',
        gender: 'male',
        role: 'Editor',
        amount: 720,
        status: 'processing',
    },
    {
        id: '72959595',
        name: 'Andrea',
        email: 'andrea@example.com',
        gender: 'female',
        role: 'Viewer',
        amount: 1650,
        status: 'success',
    },
    {
        id: '7295a738',
        name: 'Brad',
        email: 'brad@example.com',
        gender: 'male',
        role: 'Manager',
        amount: 210,
        status: 'failed',
    },
];
